language: java

# command to install dependencies
install:
  - mvn install -U -DskipTests=true -Dmaven.javadoc.skip=true -B -V
# command to run tests
script:
  - cp travis-settings.xml $HOME/.m2/settings.xml
  - mvn deploy -DskipTests